### PR TITLE
Properly set /root/.ssh to 0700

### PR DESCRIPTION
**Pull request by ramereth**
Setting this to 0750 is wrong so let's make it 700.

### CODE REVIEW

**Comment by doublej472** [comment]
Do we want `/root` or anything below it to be viewable by unprivileged users? Having it visible at all seems like a security risk

**Comment by ramereth** [comment]
@doublej472 we're not creating the ``/root` directory here (the OS does that for us). only ``/root/.ssh``.

**Comment by doublej472** [comment]
The OS does create it on installation, but we can manage it afterwards. We are implicitly managing `/root` already by setting `recursive true` on the `/root/.ssh` directive, so if `/root` doesn't exist then the recipe creates it.

I'm only concerned about the security on `/root` though, I'm not sure why the OS has an insecure default for this directory. Maybe this can be an issue for OpenStack Taster?

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v1.5.1.  Have a nice day!

**Pull request merged**
