### PR TITLE
Chef 14 post-migration fixes

### PR DESCRIPTION
**Pull request by detjensrobert**

### CODE REVIEW

**Comment by detjensrobert** [comment]
I don't see `apt` or `yum` as dependencies. Are they being mentioned somewhere other than `metadata.rb` and the recipes?

**Comment by ramereth** [comment]
@detjensrobert nope, they're in ``metadata.rb``

**Comment by detjensrobert** [comment]
!bump minor *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v2.3.0.  Have a nice day!

**Pull request merged**
