### PR TITLE
Chef 14 compatibility fixes

### PR DESCRIPTION
**Pull request by Vancelot11**

### CODE REVIEW

**Comment by ramereth** [comment]
@Vancelot11 you also need to fix foodcritic:
```
chef exec foodcritic --epic-fail any .
Checking 18 files
......x...........
FC009: Resource attribute not recognised: ./recipes/_drbd.rb:32
```

**Comment by Vancelot11** [comment]
@ramereth did we ever find a workaround for that kernel_module(s)? Is there any way to be more explicit with which resource we're trying to use?

**Comment by ramereth** [comment]
@Vancelot11 yes, we had decided to make our own ``osl_kernel_module`` resource in the base cookbook until this gets resolved upstream. I think @dmgasper was going to work on that.

**Comment by ramereth** [comment]
[Chef 14: ganeti](https://trello.com/c/zaYRD6dg/1366-chef-14-ganeti)

**Comment by ramereth** [comment]
@Vancelot11 so after looking into this more, we can safely ignore this foodcritic issue. We don't need to make a new wrapper resource for this afterall. Can you please revert the commit which removes the resource and apply those changes? See what @dmgasper did in osl-syslog for a reference.

**Pull request closed without merging**
